listen: localhost:3003
mcpServers:
  context7:
    type: http
    url: https://mcp.context7.com/mcp
  time:
    type: stdio
    command: docker
    args:
      - run
      - -i
      - --rm
      - mcp/time
  serena:
    type: stdio
    command: docker
    args:
      - run
      - -i
      - --rm
      - --network
      - host
      - -p
      - ${SERENA_DASHBOARD_PORT}:${SERENA_DASHBOARD_PORT}
      - --env
      - SERENA_DASHBOARD_PORT=${SERENA_DASHBOARD_PORT}
      - -v
      - ${SERENA_WORKING_DIR}:${SERENA_WORKING_DIR}
      - -v
      - serena_home:/workspace/serena
      - ghcr.io/oraios/serena:latest
      - serena
      - start-mcp-server
  github:
    type: http
    url: https://api.githubcopilot.com/mcp/
    headers:
      Authorization: "Bearer ${GITHUB_MCP_PAT}"
profiles:
  default:
    serena: {}
    context7:
      tools:
        - resolve-library-id
    time:
      prefix: false
      tools:
        - get_current_time
    github-readonly-profile-with-prefix:
      prefix: gh__
      tools:
        - github__list_commits
    github-readonly-profile-wo-prefix:
      prefix: false
      tools:
        - list_commits
    github-readonly-profile-with-default-prefix:
      tools:
        - github__list_commits
  github-readonly-profile-with-prefix:
    github:
      prefix: github__
      tools:
        - list_commits
  github-readonly-profile-wo-prefix:
    github:
      prefix: false
      tools:
        - list_commits
  github-readonly-profile-with-default-prefix:
    github:
      tools:
        - list_commits
